spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.qzsjioippufviyokszob
spring.datasource.password=UZ636jk^7Mdn!NYoqS27r7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB